project:
  type: website
  output-dir: docs

website:
  title: "Music And Organ"
  navbar:
    right:
      - href: index.qmd
        icon: person-square
        text: Home
      - href: test.qmd
        icon: question-circle-fill
        text: Test
      - href: about.qmd
        icon: bookmark-fill
        text: About

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

