project:
  type: website
  output-dir: docs

website:
  title: "Music and Organ"
  search: false
  navbar:
    right:
      - href: about.qmd
        icon: bookmark-fill
        text: About
        
      - href: test.qmd
        icon: question-circle-fill
        text: Test
        
      - href: projects.qmd
        icon: controller
        text: Projects
        
      - icon: github
        href: https://github.com/NoteHeart
        text: GitHub
format:
  html:
    theme: darkly
    css: styles.css
    toc: false

editor: visual

