project:
  type: website
  output-dir: docs

website:
  title: "Music And Organ"
  navbar:
    right:
      - href: about.qmd
        icon: bookmark-fill
        text: About
      - href: test.qmd
        icon: question-circle-fill
        text: Test
format:
  html:
    theme: darkly
    css: styles.css
    toc: false

editor: visual

